version: '3'

tasks:
  rustc:
    desc: Install custom rustc toolchain
    cmds:
    - ./rustc/install.sh
    
  run:
    dir: '{{.USER_WORKING_DIR}}'
    desc: Run megaton-hammer
    cmds:
    - echo "TODO"

  doc:
    desc: Build documentation into the docs/ directory
    cmds:
    - echo "TODO"
