[package]
name = "megaton-hermit"
version = "0.0.0"
edition = "2021"
description = "Proxy to forward syscalls to NNSDK"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
